baseURL = "http://pl-fintual-staging.herokuapp.com"
languageCode = "es"
DefaultContentLanguage= "es"
title = "Contenido Fintual"
theme = "hugo-theme-blueberry-detox"

[params]
  author = "Fintual, Inc."
