baseURL = "http://blog.fintual.com/"
languageCode = "es"
DefaultContentLanguage= "es"
title = "El periódico de Fintual Inc."
theme = "pixyll"

[params]
  author = "Fintual, Inc."
[menu]
  [[menu.main]]
      name = "Home"
      weight = 1
      identifier = "home"
      url = "/"
