---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: tag_list
  name: tags
  label: Tags
  description: Los tags son palabras clave del post
pages:
- content/blog/juan-cristobal-guarello---para-los-grandes-hombres-de-negocios--especular-es-mejor-que-el-sexo-.md
- content/c/que-son-los-fondos-mutuos.md
- content/c/por-que-no-te-convienen-los-fondos-mutuos.md
