---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: tag_list
  name: tags
  label: Tags
  description: Los tags son palabras clave del post
pages:
- content/como-fue-que-terminamos-haciendo-una-institucion-financiera-regulada.md
